# https://docusaurus.io/docs/deployment#triggering-deployment-with-github-actions
name: validate

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          
      - uses: actions/setup-node@v5
        with:
          node-version: "20.x"
          cache: yarn
          cache-dependency-path: foomo/yarn.lock

      - name: Enable Corepack
        run: corepack enable
          
      - name: Test Build
        working-directory: foomo
        run: |
          yarn install --frozen-lockfile
          npm run build
